use crate::timer::TimerState;
use ksni::{Handle, MenuItem, ToolTip, Tray, TrayService, menu::*};
use std::sync::mpsc::Sender;

/// Events generated by the system tray menu actions.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrayEvent {
    Start,
    Pause,
    Resume,
    Stop,
    Exit,
}

/// The system tray implementation using `ksni`.
pub struct WorkTimerTray {
    state: TimerState,
    elapsed: std::time::Duration,
    sender: Sender<TrayEvent>,
}

impl WorkTimerTray {
    /// Creates a new system tray instance.
    pub fn new(state: TimerState, sender: Sender<TrayEvent>) -> Self {
        Self {
            state,
            elapsed: std::time::Duration::ZERO,
            sender,
        }
    }

    /// Spawns the system tray service and returns the handle for updates.
    pub fn run(self) -> Handle<Self> {
        let service = TrayService::new(self);
        let handle = service.handle();
        service.spawn();
        handle
    }

    /// Updates the tray's internal state (which automatically updates the menu and icon).
    pub fn update_state(&mut self, state: TimerState, elapsed: std::time::Duration) {
        self.state = state;
        self.elapsed = elapsed;
    }
}

fn format_duration(d: std::time::Duration) -> String {
    let secs = d.as_secs();
    let hours = secs / 3600;
    let minutes = (secs % 3600) / 60;
    let seconds = secs % 60;
    format!("{:02}:{:02}:{:02}", hours, minutes, seconds)
}

impl Tray for WorkTimerTray {
    fn id(&self) -> String {
        "worktimer".into()
    }

    fn title(&self) -> String {
        "WorkTimer".into()
    }

    fn icon_name(&self) -> String {
        match self.state {
            TimerState::Idle => "media-playback-stop".into(),
            TimerState::Running => "media-playback-start".into(),
            TimerState::Paused => "media-playback-pause".into(),
            TimerState::Stopped => "media-playback-stop".into(),
        }
    }

    fn tool_tip(&self) -> ToolTip {
        let title = "WorkTimer".to_string();
        let description = match self.state {
            TimerState::Running => format!("Running: {}", format_duration(self.elapsed)),
            TimerState::Paused => format!("Paused: {}", format_duration(self.elapsed)),
            TimerState::Idle => "Idle".to_string(),
            TimerState::Stopped => "Stopped".to_string(),
        };
        ToolTip {
            title,
            description,
            ..Default::default()
        }
    }

    fn menu(&self) -> Vec<MenuItem<Self>> {
        let time_label = match self.state {
            TimerState::Running => format!("Time: {}", format_duration(self.elapsed)),
            TimerState::Paused => format!("Time: {} (Paused)", format_duration(self.elapsed)),
            TimerState::Idle => "Time: 00:00:00 (Idle)".into(),
            TimerState::Stopped => "Time: 00:00:00 (Stopped)".into(),
        };

        let status_item = StandardItem {
            label: time_label,
            enabled: false,
            ..Default::default()
        };

        let start_item = StandardItem {
            label: "Start".into(),
            enabled: matches!(self.state, TimerState::Idle | TimerState::Stopped),
            activate: Box::new(|this: &mut Self| {
                let _ = this.sender.send(TrayEvent::Start);
            }),
            ..Default::default()
        };

        let pause_item = StandardItem {
            label: "Pause".into(),
            enabled: matches!(self.state, TimerState::Running),
            activate: Box::new(|this: &mut Self| {
                let _ = this.sender.send(TrayEvent::Pause);
            }),
            ..Default::default()
        };

        let resume_item = StandardItem {
            label: "Resume".into(),
            enabled: matches!(self.state, TimerState::Paused),
            activate: Box::new(|this: &mut Self| {
                let _ = this.sender.send(TrayEvent::Resume);
            }),
            ..Default::default()
        };

        let stop_item = StandardItem {
            label: "Stop".into(),
            enabled: matches!(self.state, TimerState::Running | TimerState::Paused),
            activate: Box::new(|this: &mut Self| {
                let _ = this.sender.send(TrayEvent::Stop);
            }),
            ..Default::default()
        };

        let exit_item = StandardItem {
            label: "Exit".into(),
            activate: Box::new(|this: &mut Self| {
                let _ = this.sender.send(TrayEvent::Exit);
            }),
            ..Default::default()
        };

        vec![
            status_item.into(),
            MenuItem::Separator,
            start_item.into(),
            pause_item.into(),
            resume_item.into(),
            stop_item.into(),
            MenuItem::Separator,
            exit_item.into(),
        ]
    }
}
